# BetaQuick FCCC Document API
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# You can specify a custom docker image from Docker Hub as your build environment.
image: betaquick/node_sonar

pipelines:
  default:
  - step:
      caches:
      - node
      script: # Modify the commands below to build your repository.
      - npm install
      - npm run build
      - npm run test
  - step:
      name: Build and push docker image to Docker Hub
      caches:
        - node
      script:
        - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        - docker build -f Dockerfile -t $DOCKER_IMAGE:latest .
        - docker push $DOCKER_IMAGE:latest
      services:
        - docker
